# info_flow_zipper.jl — Drosophila Fig-6 info-flow on the FAFB connectome,
# implemented as direct PathMap zipper algebra. Mirrors upstream MORK's
# aunt-kg pattern (~/JuliaAGI/dev-zone/MORK/benchmarks/aunt-kg/src/main.rs):
# read_zipper_at_path + per-pre prefix-narrowed subtrie walk, µs-scale per op,
# O(E) total work — each edge walked once when its `pre` first becomes reached.
#
# Why this layer (not the MeTTa interpreter, not the exec calculus)?
# The connectome's recursive aggregating reachability is a relational query
# over a large trie — the same shape upstream's aunt-kg/logic-query benchmarks
# use. Both upstream Rust and the Julia port expose the zipper lattice
# primitives directly (graft/restrict/meet/subtract/descend_to/to_next_val!);
# those are the high-speed substrate path. The interpreter (`core_match`'s
# O(N) walk) and the exec calculus's ProductZipper cartesian iteration are
# the wrong abstractions for this workload — see STAGE2_RESULTS.md
# "Tractability boundary" for the history.
#
# Atoms ingested:  (syn <pre> <post> <syn_count>)
# Seeds:           afferent neuron ids for a modality (one per line)
# Output:          Dict{neuron_id => rank} matching the deterministic awk oracle.
#
# Measured on a workstation (3.73M-edge full FAFB v783, 134k+ post-neurons):
#   load (bulk_load_syn! via set_val_at!):  ~3 min
#   tin (one Σ pass over all syn atoms):    ~30 s
#   thermosensory (29 seeds) to fixed pt:   ~0.1 s, 8 rounds, 0 rank-mismatches
#   gustatory     (408 seeds) capped @30 :  ~10 s, 4540 reached, 0 rank-mismatches
# (Compare: earlier interpreter / exec-calculus attempts couldn't handle the
#  9.5k-edge gustatory K=1 subset; this runs the full 3.73M-edge graph.)
#
# Run:  julia --project=packages/MORK packages/Core/examples/connectome/info_flow_zipper.jl
# (requires /tmp/fafb_pairs.tsv + /tmp/seed_<mod>.txt + /tmp/oracle_<mod>.tsv
#  generated by ./extract_fafb_subset.sh)

using Pkg; Pkg.activate("/home/shivaji1012/PRIMUS/packages/MORK"); using MORK
using PathMap: read_zipper_at_path, zipper_to_next_val!, zipper_path, set_val_at!

# ── Byte-level helpers ────────────────────────────────────────────────────────
@inline function syn_pre_prefix(r::AbstractString) :: Vector{UInt8}
    n  = ncodeunits(r); rb = codeunits(r); sb = codeunits("syn")
    buf = Vector{UInt8}(undef, 6 + n)
    buf[1] = item_byte(ExprArity(UInt8(4)))
    buf[2] = item_byte(ExprSymbol(UInt8(3)))
    @inbounds for i in 1:3; buf[2+i] = sb[i]; end
    buf[6] = item_byte(ExprSymbol(UInt8(n)))
    @inbounds for i in 1:n; buf[6+i] = rb[i]; end
    buf
end

const SYN_PREFIX = vcat(UInt8[item_byte(ExprArity(UInt8(4))), item_byte(ExprSymbol(UInt8(3)))], codeunits("syn"))

@inline function parse_post_cnt(rel::Vector{UInt8})
    isempty(rel) && return nothing
    t1 = byte_item(rel[1]); t1 isa ExprSymbol || return nothing
    plen = Int(t1.size); pos = 2 + plen; pos > length(rel) && return nothing
    post = String(@view rel[2:1+plen])
    t2 = byte_item(rel[pos]); t2 isa ExprSymbol || return nothing
    clen = Int(t2.size); pos + clen > length(rel) && return nothing
    cnt = tryparse(Int, String(@view rel[pos+1:pos+clen]))
    cnt === nothing && return nothing
    (post, cnt)
end

@inline function parse_pre_post_cnt(rel::Vector{UInt8})
    isempty(rel) && return nothing
    t1 = byte_item(rel[1]); t1 isa ExprSymbol || return nothing
    plen = Int(t1.size); pos = 2 + plen
    pos > length(rel) && return nothing
    parse_post_cnt(rel[pos:end])
end

# ── Bulk-load (syn pre post cnt) atoms DIRECTLY into the trie from TSV ────────
# Each TSV line: pre \t post \t cnt   (whatever fafb_pairs.tsv produces).
# Builds the atom's full trie path and set_val_at! — no s-expr parser overhead.
function bulk_load_syn!(s::Space, tsv_path::AbstractString) :: Int
    btm = s.btm
    n = 0
    buf = UInt8[]
    sb = codeunits("syn")
    for line in eachline(tsv_path)
        isempty(line) && continue
        t1 = findfirst('\t', line); t2 = findnext('\t', line, t1+1)
        (t1 === nothing || t2 === nothing) && continue
        pre  = SubString(line, 1, t1-1)
        post = SubString(line, t1+1, t2-1)
        cnt  = SubString(line, t2+1, lastindex(line))
        pre_b = codeunits(pre); post_b = codeunits(post); cnt_b = codeunits(cnt)
        np = length(pre_b); nq = length(post_b); nc = length(cnt_b)
        # Encode (syn pre post cnt) bytes directly:
        empty!(buf)
        push!(buf, item_byte(ExprArity(UInt8(4))))
        push!(buf, item_byte(ExprSymbol(UInt8(3))))
        append!(buf, sb)
        push!(buf, item_byte(ExprSymbol(UInt8(np))))
        append!(buf, pre_b)
        push!(buf, item_byte(ExprSymbol(UInt8(nq))))
        append!(buf, post_b)
        push!(buf, item_byte(ExprSymbol(UInt8(nc))))
        append!(buf, cnt_b)
        set_val_at!(btm, buf, MORK.UNIT_VAL)
        n += 1
    end
    n
end

function compute_tin(btm)
    tin = Dict{String, Int}()
    rz = read_zipper_at_path(btm, SYN_PREFIX)
    while zipper_to_next_val!(rz)
        pc = parse_pre_post_cnt(collect(zipper_path(rz)))
        pc === nothing && continue
        post, cnt = pc
        tin[post] = get(tin, post, 0) + cnt
    end
    tin
end

function apply_frontier!(rin::Dict{String,Int}, btm, frontier::Vector{String}) :: Int
    walked = 0
    for r in frontier
        rz = read_zipper_at_path(btm, syn_pre_prefix(r))
        while zipper_to_next_val!(rz)
            pc = parse_post_cnt(collect(zipper_path(rz)))
            pc === nothing && continue
            post, cnt = pc
            rin[post] = get(rin, post, 0) + cnt
            walked += 1
        end
    end
    walked
end

function run_flow(s::Space, seed_ids::Vector{String}, tin::Dict{String,Int};
                  threshold::Float64=0.3, max_rounds::Int=30)
    btm = s.btm
    reached = Set{String}(seed_ids)
    ranks   = Dict{String,Int}(sd => 0 for sd in seed_ids)
    rin     = Dict{String,Int}()
    t = time(); w = apply_frontier!(rin, btm, collect(seed_ids))
    println("  seed apply: ", w, " edges in ", round((time()-t)*1000, digits=1), " ms")
    rounds = 0
    for k in 1:max_rounds
        rounds = k
        next = String[]
        for (post, sr) in rin
            post in reached && continue
            st = get(tin, post, 0); st <= 0 && continue
            sr / st >= threshold || continue
            push!(next, post); push!(reached, post); ranks[post] = k
        end
        n_new = length(next)
        t = time()
        w = n_new == 0 ? 0 : apply_frontier!(rin, btm, next)
        println("  round $k: new=$n_new  walked=$w  in ", round((time()-t)*1000, digits=1), " ms")
        n_new == 0 && break
    end
    println("  flow rounds: $rounds  total reached: ", length(reached))
    ranks
end

# ── Load full FAFB once, then run multiple seed sets ──────────────────────────
function main()
    println("=== full FAFB load (3.73M edges) ===")
    s = new_space()
    t = time(); n = bulk_load_syn!(s, "/tmp/fafb_pairs.tsv")
    rss_mb = parse(Int, split(read("/proc/self/statm", String))[2]) * 4096 ÷ 1024 ÷ 1024
    println("loaded ", n, " atoms in ", round(time()-t, digits=1), "s,  RSS=", rss_mb, " MB")
    t = time(); tin = compute_tin(s.btm)
    println("tin: ", length(tin), " distinct posts in ", round(time()-t, digits=2), " s")

    for (modality, seed_file, oracle_file) in [
        ("thermosensory", "/tmp/seed_thermosensory.txt", "/tmp/oracle_thermosensory.tsv"),
        ("gustatory",     "/tmp/seed_gustatory.txt",     "/tmp/oracle_gustatory.tsv"),
    ]
        println("\n=== ", modality, " (full FAFB) ===")
        seeds = readlines(seed_file) .|> strip .|> String
        filter!(!isempty, seeds)
        println("  seeds: ", length(seeds))
        t = time(); ranks = run_flow(s, seeds, tin)
        println("  total flow time: ", round(time()-t, digits=2), " s")
        # validate
        oracle = Dict{String,Int}()
        for line in eachline(oracle_file)
            isempty(line) && continue
            id, rk = split(line, '\t')
            oracle[id] = parse(Int, rk)
        end
        hist(d) = let h = Dict{Int,Int}(); for r in values(d); h[r] = get(h,r,0)+1; end; sort(collect(h)); end
        println("  oracle hist: ", hist(oracle))
        println("  metta  hist: ", hist(ranks))
        miss  = setdiff(keys(oracle), keys(ranks))
        extra = setdiff(keys(ranks), keys(oracle))
        mism  = sum(get(ranks, k, -1) != v for (k, v) in oracle; init=0)
        println("  missing=", length(miss), "  extra=", length(extra), "  rank-mismatches=", mism)
    end
end

main()
